### ISSUE TITLE
Problem with my radar image being cut off

### ISSUE THREAD

**Issue by andreazfl** [Terri00/CS-GO-Auto-Radar#17]
I've been using the auto radar and everything else seems fine besides that the top bit of my radar gets cut off.

I think it might be to do with the size of the map (6000 x 4800)

Radar:
![de_roost_radar](https://user-images.githubusercontent.com/32404279/62512218-2523ae80-b7e5-11e9-85d3-1020db071bbd.png) 

Hammer view:
![](https://i.gyazo.com/3115f47e6fc074e904c60cc3b5454338.png)

I don't know why it happens and it would be great if someone could tell me a fix.

**Comment by Terri00** [comment]
There is a slight oversight with how the boundaries are setup; `func_detail` brushes will not be included in the calculation.

This is a bug and should be worked though at some point. But for now I recommend turning the extreme most brushes into solids so that they can correctly contribute to the boundary.

Please let me know if this fixes the issue :)

**Comment by andreazfl** [comment]
I de-func_detailed the end bits of the layout and it worked!

Thanks for the help.

![de_roost_radar](https://user-images.githubusercontent.com/32404279/62547482-43b09680-b833-11e9-90a7-a31afb110aac.png)

**Comment by Terri00** [comment]
Great :)

**Comment by SomeoneGotMyNameSoINeedMyNamesOmega** [comment]
may I ask how to de-func_detail?
